on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-examples:
    runs-on: ubuntu-latest
    env:
      ROC_VERSION: nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ROC
        run: |
          # Install ROC
          curl -fOL https://github.com/roc-lang/roc/releases/download/${ROC_VERSION}/roc_nightly-linux_x86_64-latest.tar.gz
          mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz
          tar -xzf roc_nightly.tar.gz
          rm roc_nightly.tar.gz
          mv roc_nightly* roc_nightly

      - name: Check ROC version
        run: ./roc_nightly/roc version

      - name: Run all tests
        run: ROC=./roc_nightly/roc ./ci/all_tests.sh
